header = "\n ************************************************************************\n                ------Bienvenidos a TecnoXpress ------ \n ------Mejora tu experiencia con lo mejor en Tech y accesorios------\n ************************************************************************"
closer = "\n\t\tGracias por su consulta.\n\t Aplicación creada por Equipo X - ISPC"
erroneo = "\nOpcion Incorrecta. Intente nuevamente.\n"
decorador ="\n ******************************************************"
correcto="\n\tEl campo se ha modificado correctamente.\n"
opcion="Ingrese la opción elegida: "